---
output:
  html_document:
    keep_md: true
---

Data from the publication: 


**Length-mass relationships for lake macroinvertebrates corrected for back transformation and preservation effects.**



Marlen Mährlein^1\*^, Marlene Pätzig^2\,\ 3\*^, Mario Brauns^1\,\ 4^, Andrew M. Dolman^2^


\* Authors contributed equally to the article

Corresponding author: Marlen Mährlein, e-mail: marlen.maehrlein (at) igb-berlin.de

1 Leibniz-Institute of Freshwater Ecology and Inland Fisheries (IGB), Müggelseedamm 301, 12587 Berlin, Germany 

2 Department of Freshwater Conservation, Brandenburg University of Technology Cottbus-Senftenberg (BTU), Seestr. 45, 15526 Bad Saarow, Germany

3 Institute of Landscape Hydrology, Leibniz Centre for Agricultural Landscape Research (ZALF), Eberswalder Str. 84, 15374 Müncheberg, Germany 

4 Present address: Helmholtz Centre for Environmental Research GmbH (UFZ), Brückstr. 3a, 39114 Magdeburg, Germany


*******

Data are located in folders *data/excel* and *data/csv*


Files ending in "_key" give descriptions for each variable in their corresponding "_archive" files.




